sample:
  kotlin:
    language: kotlin
    study-days: 30
  java:
    language: java
    study-days: 90
    test: javaTest

spring:
  redis:
    host: 13.125.66.120
    port: 6379
    timeout: 3000
    expire: 8